"""Merge per-pair trade CSVs into merged USD files.

Reads pair CSVs from `data/partial/` (generated by `fetch_trades.py`) and writes one
merged USD file per logical asset (e.g. `btcusd.csv`).
"""

import csv
from datetime import datetime
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

# Output asset -> list of base token symbols to merge.
# Example: merge both WBTC and cbBTC trades into one `btcusd.csv`.
ASSET_GROUPS = {
    # "btc": ["wbtc", "cbbtc"],
    "eth": ["eth", "weth"],
}

# Quote tokens (stablecoins) to merge.
TOKENS_B = ["usdc", "usdt"]

START_DATE = None  # e.g., "2024-01-01" or None for all
END_DATE = None  # e.g., "2024-12-31" or None for latest
MIN_VOLUME_USD = 100  # minimum trade volume in USD

DATA_DIR = Path(__file__).resolve().parent / "data"
PARTIAL_DIR = DATA_DIR / "partial"

# =============================================================================


def parse_date(date_str):
    if date_str is None:
        return None
    return datetime.fromisoformat(date_str)


def load_partial_trades(filepath, base_token, quote_token, output_asset):
    trades = []
    base_u = base_token.upper()

    with open(filepath) as f:
        for row in csv.DictReader(f):
            ts = datetime.fromisoformat(row["timestamp"])

            base_usd = float(row[f"{base_token}_amount_usd"])
            quote_usd = float(row[f"{quote_token}_amount_usd"])
            total_usd_volume = (base_usd + quote_usd) / 2

            direction = row["direction"]
            if direction.startswith(f"{base_u}_TO_"):
                normalized = "SELL"  # selling base for quote
            else:
                normalized = "BUY"  # buying base with quote

            trades.append(
                {
                    "unix_timestamp": int(ts.timestamp()),
                    "datetime": ts,
                    "date": ts.strftime("%Y-%m-%d %H:%M:%S"),
                    "direction": normalized,
                    "asset": output_asset,
                    "asset_amount": float(row[f"{base_token}_amount"]),
                    "usd_amount": float(row[f"{quote_token}_amount"]),
                    "price": float(
                        row[f"effective_price_{quote_token}_per_{base_token}"]
                    ),
                    "total_usd_volume": total_usd_volume,
                    "source": quote_token,
                }
            )

    return trades


def filter_trades(trades, start_date, end_date, min_volume):
    filtered = []
    for t in trades:
        if start_date and t["datetime"].date() < start_date.date():
            continue
        if end_date and t["datetime"].date() > end_date.date():
            continue
        if t["total_usd_volume"] < min_volume:
            continue
        filtered.append(t)
    return filtered


def write_csv(trades, output_path, output_asset):
    trades.sort(key=lambda t: t["unix_timestamp"], reverse=True)

    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "unix_timestamp",
                "date",
                "direction",
                f"{output_asset}_amount",
                "usd_amount",
                "price",
                "total_usd_volume",
                "source",
            ]
        )
        for t in trades:
            writer.writerow(
                [
                    t["unix_timestamp"],
                    t["date"],
                    t["direction"],
                    f"{t['asset_amount']:.8f}",
                    f"{t['usd_amount']:.2f}",
                    f"{t['price']:.2f}",
                    f"{t['total_usd_volume']:.2f}",
                    t["source"],
                ]
            )


def main():
    start = parse_date(START_DATE)
    end = parse_date(END_DATE)

    DATA_DIR.mkdir(parents=True, exist_ok=True)

    print(
        f"Start: {start.date() if start else 'All'} | End: {end.date() if end else 'Latest'} | Min volume: ${MIN_VOLUME_USD}"
    )

    for output_asset, base_tokens in ASSET_GROUPS.items():
        all_trades = []

        print(
            f"\nMerging {output_asset}: {', '.join(base_tokens)}/({', '.join(TOKENS_B)}) into {output_asset}usd"
        )

        for base_token in base_tokens:
            for quote_token in TOKENS_B:
                path = PARTIAL_DIR / f"{base_token}-{quote_token}.csv"
                if not path.exists():
                    print(f"  Missing: {path}")
                    continue

                trades = load_partial_trades(
                    path, base_token, quote_token, output_asset
                )
                print(f"  Loaded {len(trades)} trades from {base_token}-{quote_token}")
                all_trades.extend(trades)

        print(f"  Total: {len(all_trades)} trades")

        filtered = filter_trades(all_trades, start, end, MIN_VOLUME_USD)
        print(f"  After filtering: {len(filtered)} trades")

        if not filtered:
            continue

        oldest = min(t["datetime"] for t in filtered)
        newest = max(t["datetime"] for t in filtered)
        buys = sum(1 for t in filtered if t["direction"] == "BUY")
        sells = len(filtered) - buys

        print(f"  Date range: {oldest.date()} to {newest.date()}")
        print(f"  BUY: {buys} | SELL: {sells}")

        output_path = DATA_DIR / f"{output_asset}usd.csv"
        write_csv(filtered, output_path, output_asset)
        print(f"  Written to {output_path}")


if __name__ == "__main__":
    main()
